// Shared fallback data for dropdown options, resource profiles, opportunities, work items, etc.
// Ensures that when database is initializing or unavailable, the application gracefully functions without 500 errors

export const FALLBACK_DROPDOWN_OPTIONS = [
  { id: 1, category: 'opportunity_type', option_name: 'Renewal', sort_order: 1, color: '#3b82f6', active: true },
  { id: 2, category: 'opportunity_type', option_name: 'New Business', sort_order: 2, color: '#10b981', active: true },
  { id: 3, category: 'opportunity_type', option_name: 'Change Request', sort_order: 3, color: '#8b5cf6', active: true },
  { id: 4, category: 'source', option_name: 'Inbound Inquiry', sort_order: 1, color: '#10b981', active: true },
  { id: 5, category: 'source', option_name: 'Sales Outreach', sort_order: 2, color: '#3b82f6', active: true },
  { id: 6, category: 'source', option_name: 'Partner Channel', sort_order: 3, color: '#8b5cf6', active: true },
  { id: 7, category: 'source', option_name: 'Existing Account Expansion', sort_order: 4, color: '#6366f1', active: true },
  { id: 8, category: 'source', option_name: 'Referral', sort_order: 5, color: '#f59e0b', active: true },
  { id: 9, category: 'deal_stage', option_name: 'Discovery', sort_order: 1, color: '#3b82f6', active: true },
  { id: 10, category: 'deal_stage', option_name: 'Submitted to Client', sort_order: 2, color: '#06b6d4', active: true },
  { id: 11, category: 'deal_stage', option_name: 'POC(Proof Of Concept)', sort_order: 3, color: '#8b5cf6', active: true },
  { id: 12, category: 'deal_stage', option_name: 'Won', sort_order: 4, color: '#10b981', active: true },
  { id: 13, category: 'deal_stage', option_name: 'Lost', sort_order: 5, color: '#ef4444', active: true },
  { id: 14, category: 'priority', option_name: 'Low', sort_order: 1, color: '#22c55e', active: true },
  { id: 15, category: 'priority', option_name: 'Medium', sort_order: 2, color: '#eab308', active: true },
  { id: 16, category: 'priority', option_name: 'High', sort_order: 3, color: '#f97316', active: true },
  { id: 17, category: 'priority', option_name: 'Critical', sort_order: 4, color: '#ef4444', active: true },
  { id: 18, category: 'complexity', option_name: 'Low', sort_order: 1, color: '#22c55e', active: true },
  { id: 19, category: 'complexity', option_name: 'Medium', sort_order: 2, color: '#eab308', active: true },
  { id: 20, category: 'complexity', option_name: 'High', sort_order: 3, color: '#f97316', active: true },
  { id: 21, category: 'complexity', option_name: 'Complex', sort_order: 4, color: '#ef4444', active: true },
  { id: 22, category: 'work_category', option_name: 'Proposal Writing', sort_order: 1, color: '#3b82f6', active: true },
  { id: 23, category: 'work_category', option_name: 'Product Demo', sort_order: 2, color: '#ec4899', active: true },
  { id: 24, category: 'work_category', option_name: 'Technical Scoping', sort_order: 3, color: '#8b5cf6', active: true },
  { id: 25, category: 'work_category', option_name: 'Pricing', sort_order: 4, color: '#06b6d4', active: true },
  { id: 26, category: 'work_category', option_name: 'Documentation', sort_order: 5, color: '#10b981', active: true },
  { id: 27, category: 'deliverable_type', option_name: 'RFP Response', sort_order: 1, color: '#ef4444', active: true },
  { id: 28, category: 'deliverable_type', option_name: 'Non RFP Response', sort_order: 2, color: '#3b82f6', active: true },
  { id: 29, category: 'deliverable_type', option_name: 'Proposal', sort_order: 3, color: '#f97316', active: true },
  { id: 30, category: 'deliverable_type', option_name: 'Presentation Deck', sort_order: 4, color: '#22c55e', active: true },
  { id: 31, category: 'deliverable_type', option_name: 'Brochure', sort_order: 5, color: '#2563eb', active: true },
  { id: 32, category: 'estimation_confidence', option_name: 'High', sort_order: 1, color: '#22c55e', active: true },
  { id: 33, category: 'estimation_confidence', option_name: 'Medium', sort_order: 2, color: '#eab308', active: true },
  { id: 34, category: 'estimation_confidence', option_name: 'Low', sort_order: 3, color: '#ef4444', active: true },
  { id: 35, category: 'task_status', option_name: 'Not Started', sort_order: 1, color: '#6b7280', active: true },
  { id: 36, category: 'task_status', option_name: 'In Progress', sort_order: 2, color: '#3b82f6', active: true },
  { id: 37, category: 'task_status', option_name: 'Review', sort_order: 3, color: '#a855f7', active: true },
  { id: 38, category: 'task_status', option_name: 'Blocked', sort_order: 4, color: '#ef4444', active: true },
  { id: 39, category: 'task_status', option_name: 'Completed', sort_order: 5, color: '#10b981', active: true },
  { id: 40, category: 'task_status', option_name: 'Cancelled', sort_order: 6, color: '#64748b', active: true },
  { id: 41, category: 'task_status', option_name: 'Terminated', sort_order: 7, color: '#ef4444', active: true },
  { id: 42, category: 'trigger_source', option_name: 'Client Feedback', sort_order: 1, color: '#3b82f6', active: true },
  { id: 43, category: 'trigger_source', option_name: 'Scope Expansion', sort_order: 2, color: '#10b981', active: true },
  { id: 44, category: 'trigger_source', option_name: 'Internal QA Review', sort_order: 3, color: '#f59e0b', active: true },
  { id: 45, category: 'trigger_source', option_name: 'Competitor Pressure', sort_order: 4, color: '#ec4899', active: true },
  { id: 46, category: 'trigger_source', option_name: 'Executive Mandate', sort_order: 5, color: '#8b5cf6', active: true },
  { id: 47, category: 'reason_category', option_name: 'Commercial Negotiation', sort_order: 1, color: '#059669', active: true },
  { id: 48, category: 'reason_category', option_name: 'Technical Clarification', sort_order: 2, color: '#2563eb', active: true },
  { id: 49, category: 'reason_category', option_name: 'Timeline Compression', sort_order: 3, color: '#d97706', active: true },
  { id: 50, category: 'reason_category', option_name: 'Scope Refinement', sort_order: 4, color: '#7c3aed', active: true },
  { id: 51, category: 'version_type', option_name: 'Internal Draft', sort_order: 1, color: '#6b7280', active: true },
  { id: 52, category: 'version_type', option_name: 'Client Submission', sort_order: 2, color: '#2563eb', active: true },
  { id: 53, category: 'version_type', option_name: 'Final Contract Version', sort_order: 3, color: '#16a34a', active: true },
  { id: 54, category: 'deadline_impact', option_name: 'No Impact', sort_order: 1, color: '#16a34a', active: true },
  { id: 55, category: 'deadline_impact', option_name: 'Minor Delay (< 3 Days)', sort_order: 2, color: '#d97706', active: true },
  { id: 56, category: 'deadline_impact', option_name: 'Major Delay (> 3 Days)', sort_order: 3, color: '#ea580c', active: true },
  { id: 57, category: 'deadline_impact', option_name: 'Critical Block / Reschedule', sort_order: 4, color: '#dc2626', active: true },
  { id: 58, category: 'feedback_from', option_name: 'Client Decision Maker', sort_order: 1, color: '#2563eb', active: true },
  { id: 59, category: 'feedback_from', option_name: 'Sales Account Manager', sort_order: 2, color: '#4f46e5', active: true },
  { id: 60, category: 'feedback_from', option_name: 'External Consultant', sort_order: 3, color: '#0d9488', active: true },
  { id: 61, category: 'feedback_from', option_name: 'Technical Review Panel', sort_order: 4, color: '#7c3aed', active: true },
  { id: 62, category: 'feedback_type', option_name: 'Clarification Request', sort_order: 1, color: '#3b82f6', active: true },
  { id: 63, category: 'feedback_type', option_name: 'Commercial Adjustment', sort_order: 2, color: '#10b981', active: true },
  { id: 64, category: 'feedback_type', option_name: 'Scope Revision', sort_order: 3, color: '#f59e0b', active: true },
  { id: 65, category: 'feedback_type', option_name: 'Defect / Error Correction', sort_order: 4, color: '#ef4444', active: true },
  { id: 66, category: 'severity', option_name: 'Low', sort_order: 1, color: '#22c55e', active: true },
  { id: 67, category: 'severity', option_name: 'Medium', sort_order: 2, color: '#eab308', active: true },
  { id: 68, category: 'severity', option_name: 'High', sort_order: 3, color: '#f97316', active: true },
  { id: 69, category: 'severity', option_name: 'Critical', sort_order: 4, color: '#ef4444', active: true },
  { id: 70, category: 'feedback_status', option_name: 'Open', sort_order: 1, color: '#3b82f6', active: true },
  { id: 71, category: 'feedback_status', option_name: 'In Progress', sort_order: 2, color: '#f59e0b', active: true },
  { id: 72, category: 'feedback_status', option_name: 'Resolved', sort_order: 3, color: '#10b981', active: true },
  { id: 73, category: 'role', option_name: 'Admin', sort_order: 1, color: '#ef4444', active: true },
  { id: 74, category: 'role', option_name: 'Presales Owner', sort_order: 2, color: '#8b5cf6', active: true },
  { id: 75, category: 'role', option_name: 'Sales Owner', sort_order: 3, color: '#3b82f6', active: true },
  { id: 76, category: 'role', option_name: 'Team Member', sort_order: 4, color: '#10b981', active: true },
  { id: 77, category: 'seniority', option_name: 'Principal Consultant', sort_order: 1, color: '#ef4444', active: true },
  { id: 78, category: 'seniority', option_name: 'Senior Consultant', sort_order: 2, color: '#8b5cf6', active: true },
  { id: 79, category: 'seniority', option_name: 'Consultant', sort_order: 3, color: '#3b82f6', active: true },
  { id: 80, category: 'seniority', option_name: 'Associate', sort_order: 4, color: '#10b981', active: true },
  { id: 81, category: 'department', option_name: 'Presales Solutions', sort_order: 1, color: '#8b5cf6', active: true },
  { id: 82, category: 'department', option_name: 'Enterprise Sales', sort_order: 2, color: '#3b82f6', active: true },
  { id: 83, category: 'department', option_name: 'Delivery / Consulting', sort_order: 3, color: '#10b981', active: true }
];

export const FALLBACK_RESOURCE_PROFILES = [
  {
    id: 1,
    username: 'admin',
    name: 'Adhesh',
    role_name: 'Admin',
    role_color: '#ef4444',
    seniority_name: 'Principal Consultant',
    department_name: 'Presales Solutions',
    weekly_capacity_hours: 40.0,
    standard_focus: 'Management, Solution Architecture',
    standard_focus_area: 'Management, Solution Architecture',
    skills: 'Management, Architecture, Strategy',
    password: 'admin123',
    is_active: true
  },
  {
    id: 2,
    username: 'jane_doe',
    name: 'Jane Doe',
    role_name: 'Presales Owner',
    role_color: '#8b5cf6',
    seniority_name: 'Senior Consultant',
    department_name: 'Presales Solutions',
    weekly_capacity_hours: 45.0,
    standard_focus: 'RFPs, Cloud Architecture',
    standard_focus_area: 'RFPs, Cloud Architecture',
    skills: 'RFPs, Cloud Architecture',
    password: 'jane123',
    is_active: true
  },
  {
    id: 3,
    username: 'trisha_devadhe',
    name: 'Trisha Devadhe',
    role_name: 'Team Member',
    role_color: '#10b981',
    seniority_name: 'Senior Consultant',
    department_name: 'Presales Solutions',
    weekly_capacity_hours: 40.0,
    standard_focus: 'RFPs, Cloud Architecture',
    standard_focus_area: 'RFPs, Cloud Architecture',
    skills: 'RFPs, Solutioning',
    password: 'trisha123',
    is_active: true
  },
  {
    id: 4,
    username: 'john_smith',
    name: 'John Smith',
    role_name: 'Sales Owner',
    role_color: '#3b82f6',
    seniority_name: 'Principal Consultant',
    department_name: 'Enterprise Sales',
    weekly_capacity_hours: 40.0,
    standard_focus: 'Sales, Relationship Management',
    standard_focus_area: 'Sales, Relationship Management',
    skills: 'Enterprise Sales, Account Management',
    password: 'john123',
    is_active: true
  },
  {
    id: 5,
    username: 'vartika_jadon',
    name: 'Vartika Jadon',
    role_name: 'Team Member',
    role_color: '#10b981',
    seniority_name: 'Consultant',
    department_name: 'Delivery / Consulting',
    weekly_capacity_hours: 35.0,
    standard_focus: 'Demo Prep, Frontend',
    standard_focus_area: 'Demo Prep, Frontend',
    skills: 'Prototyping, Demo Setup',
    password: 'vartika123',
    is_active: true
  },
  {
    id: 6,
    username: 'alice_williams',
    name: 'Alice Williams',
    role_name: 'Team Member',
    role_color: '#10b981',
    seniority_name: 'Associate',
    department_name: 'Delivery / Consulting',
    weekly_capacity_hours: 40.0,
    standard_focus: 'Pricing, Excel Modeling',
    standard_focus_area: 'Pricing, Excel Modeling',
    skills: 'Pricing Models, Analytics',
    password: 'alice123',
    is_active: true
  },
  {
    id: 7,
    username: 'vikrant_dhuriya',
    name: 'Vikrant Dhuriya',
    role_name: 'Team Member',
    role_color: '#10b981',
    seniority_name: 'Consultant',
    department_name: 'Delivery / Consulting',
    weekly_capacity_hours: 40.0,
    standard_focus: 'Solution Architecture & Integration',
    standard_focus_area: 'Solution Architecture & Integration',
    skills: 'Integration, Cloud Services',
    password: 'vikrant123',
    is_active: true
  },
  {
    id: 8,
    username: 'divyam_malliwal',
    name: 'Divyam Malliwal',
    role_name: 'Team Member',
    role_color: '#10b981',
    seniority_name: 'Consultant',
    department_name: 'Delivery / Consulting',
    weekly_capacity_hours: 40.0,
    standard_focus: 'Technical Consulting & Delivery',
    standard_focus_area: 'Technical Consulting & Delivery',
    skills: 'Technical Consultation, Fullstack',
    password: 'divyam123',
    is_active: true
  },
  {
    id: 9,
    username: 'finance_team',
    name: 'Finance Team',
    role_name: 'Finance Team',
    role_color: '#f59e0b',
    seniority_name: 'Senior Consultant',
    department_name: 'Presales Solutions',
    weekly_capacity_hours: 40.0,
    standard_focus: 'Financial & Commercial Review, Deal Approvals',
    standard_focus_area: 'Financial & Commercial Review, Deal Approvals',
    skills: 'Commercial Pricing, Deal Approvals',
    password: 'finance123',
    is_active: true
  }
];

export const FALLBACK_OPPORTUNITIES = [
  {
    id: 1,
    opportunity_name: 'Global Cloud Modernization',
    company: 'Apex Financial Services',
    opportunity_type_id: 2,
    opportunity_type_name: 'New Business',
    opportunity_type_color: '#10b981',
    deliverable_type_id: 27,
    deliverable_type_name: 'RFP Response',
    deliverable_type_color: '#ef4444',
    primary_sales_owner: 'john_smith',
    secondary_sales_owners: '',
    source_id: 4,
    source_name: 'Inbound Inquiry',
    source_color: '#10b981',
    deal_stage_id: 10,
    deal_stage_name: 'Submitted to Client',
    deal_stage_color: '#06b6d4',
    priority_id: 16,
    priority_name: 'High',
    priority_color: '#f97316',
    estimated_deal_value: 240000.0,
    contract_tenure: 12,
    win_probability: 70,
    complexity_id: 20,
    complexity_name: 'High',
    complexity_color: '#f97316',
    received_date: '2026-09-15',
    target_submission_date: '2026-10-25',
    internal_review_date: '2026-10-20',
    presales_owner: 'jane_doe',
    supporting_presales_members: 'trisha_devadhe, vartika_jadon',
    summary: 'Multi-region Kubernetes migration and cloud architecture modernization proposal.',
    risks: 'Tight submission timeline and complex compliance requirements.',
    special_instructions: 'Ensure SOC2 and PCI-DSS compliance frameworks are explicitly highlighted.',
    tcv_amount: 240000.0,
    tcv_currency: 'USD',
    delivery_team: 'Cloud Core Practice',
    project_type: 'Fixed Bid',
    finance_status: 'Approved',
    attachments: '[]',
    revision_counter: 0,
    commercial_revision_counter: 0
  },
  {
    id: 2,
    opportunity_name: 'Enterprise CRM Transformation',
    company: 'Nexus Logistics Global',
    opportunity_type_id: 1,
    opportunity_type_name: 'Renewal',
    opportunity_type_color: '#3b82f6',
    deliverable_type_id: 29,
    deliverable_type_name: 'Proposal',
    deliverable_type_color: '#f97316',
    primary_sales_owner: 'john_smith',
    secondary_sales_owners: '',
    source_id: 7,
    source_name: 'Existing Account Expansion',
    source_color: '#6366f1',
    deal_stage_id: 11,
    deal_stage_name: 'POC(Proof Of Concept)',
    deal_stage_color: '#8b5cf6',
    priority_id: 15,
    priority_name: 'Medium',
    priority_color: '#eab308',
    estimated_deal_value: 125000.0,
    contract_tenure: 24,
    win_probability: 60,
    complexity_id: 19,
    complexity_name: 'Medium',
    complexity_color: '#eab308',
    received_date: '2026-09-20',
    target_submission_date: '2026-11-05',
    internal_review_date: '2026-10-30',
    presales_owner: 'trisha_devadhe',
    supporting_presales_members: 'vikrant_dhuriya',
    summary: 'Salesforce enterprise implementation and custom ERP data sync connectors.',
    risks: 'Legacy database integration latency.',
    special_instructions: 'Include POC demonstration milestones in the commercial section.',
    tcv_amount: 125000.0,
    tcv_currency: 'USD',
    delivery_team: 'Enterprise Applications',
    project_type: 'Time & Materials',
    finance_status: 'Pending',
    attachments: '[]',
    revision_counter: 1,
    commercial_revision_counter: 0
  },
  {
    id: 3,
    opportunity_name: 'AI Data Intelligence Engine',
    company: 'Vanguard Biopharma',
    opportunity_type_id: 2,
    opportunity_type_name: 'New Business',
    opportunity_type_color: '#10b981',
    deliverable_type_id: 30,
    deliverable_type_name: 'Presentation Deck',
    deliverable_type_color: '#22c55e',
    primary_sales_owner: 'john_smith',
    secondary_sales_owners: '',
    source_id: 5,
    source_name: 'Sales Outreach',
    source_color: '#3b82f6',
    deal_stage_id: 9,
    deal_stage_name: 'Discovery',
    deal_stage_color: '#3b82f6',
    priority_id: 17,
    priority_name: 'Critical',
    priority_color: '#ef4444',
    estimated_deal_value: 380000.0,
    contract_tenure: 36,
    win_probability: 50,
    complexity_id: 21,
    complexity_name: 'Complex',
    complexity_color: '#ef4444',
    received_date: '2026-10-01',
    target_submission_date: '2026-11-15',
    internal_review_date: '2026-11-10',
    presales_owner: 'admin',
    supporting_presales_members: 'divyam_malliwal, vartika_jadon',
    summary: 'Generative AI pipeline and clinical document search solution.',
    risks: 'HIPAA compliant cloud storage configuration needed.',
    special_instructions: 'Highlight data privacy controls and on-premise model deployment options.',
    tcv_amount: 380000.0,
    tcv_currency: 'USD',
    delivery_team: 'Data & AI Practice',
    project_type: 'Fixed Bid',
    finance_status: 'Pending',
    attachments: '[]',
    revision_counter: 0,
    commercial_revision_counter: 0
  }
];

export const FALLBACK_WORK_ITEMS = [
  {
    id: 1,
    opportunity_id: 1,
    opportunity_name: 'Global Cloud Modernization',
    company: 'Apex Financial Services',
    work_category_id: 22,
    work_category_name: 'Proposal Writing',
    work_category_color: '#3b82f6',
    title: 'Executive Summary & Compliance Matrix Drafting',
    description: 'Draft the multi-region AWS cloud migration architecture overview.',
    deliverable_type_id: 27,
    deliverable_type_name: 'RFP Response',
    assigned_to: 'jane_doe',
    reviewer: 'admin',
    collaborators: 'trisha_devadhe',
    priority_id: 16,
    priority_name: 'High',
    priority_color: '#f97316',
    start_date: '2026-09-18',
    due_date: '2026-10-22',
    estimated_hours: 24.0,
    estimation_confidence_id: 32,
    estimation_confidence_name: 'High',
    is_revision_work: false,
    revision_number: 0,
    trigger_id: null,
    trigger_name: null,
    status_id: 36,
    status_name: 'In Progress',
    status_color: '#3b82f6',
    blocker_reason: null,
    deliverable_link: '',
    notes: 'Initial technical draft ready for preliminary review.'
  },
  {
    id: 2,
    opportunity_id: 1,
    opportunity_name: 'Global Cloud Modernization',
    company: 'Apex Financial Services',
    work_category_id: 24,
    work_category_name: 'Technical Scoping',
    work_category_color: '#8b5cf6',
    title: 'Kubernetes Infrastructure Cost & Sizing Analysis',
    description: 'Model resource footprint across EKS clusters and storage tiers.',
    deliverable_type_id: 27,
    deliverable_type_name: 'RFP Response',
    assigned_to: 'trisha_devadhe',
    reviewer: 'jane_doe',
    collaborators: 'vartika_jadon',
    priority_id: 16,
    priority_name: 'High',
    priority_color: '#f97316',
    start_date: '2026-09-20',
    due_date: '2026-10-20',
    estimated_hours: 18.0,
    estimation_confidence_id: 32,
    estimation_confidence_name: 'High',
    is_revision_work: false,
    revision_number: 0,
    trigger_id: null,
    trigger_name: null,
    status_id: 36,
    status_name: 'In Progress',
    status_color: '#3b82f6',
    blocker_reason: null,
    deliverable_link: '',
    notes: 'Calculations verified against AWS pricing calculator.'
  },
  {
    id: 3,
    opportunity_id: 2,
    opportunity_name: 'Enterprise CRM Transformation',
    company: 'Nexus Logistics Global',
    work_category_id: 23,
    work_category_name: 'Product Demo',
    work_category_color: '#ec4899',
    title: 'Interactive POC Workflow Demonstration Prep',
    description: 'Configure sandbox instance with sample logistics order workflow data.',
    deliverable_type_id: 29,
    deliverable_type_name: 'Proposal',
    assigned_to: 'vartika_jadon',
    reviewer: 'trisha_devadhe',
    collaborators: '',
    priority_id: 15,
    priority_name: 'Medium',
    priority_color: '#eab308',
    start_date: '2026-09-25',
    due_date: '2026-10-28',
    estimated_hours: 16.0,
    estimation_confidence_id: 33,
    estimation_confidence_name: 'Medium',
    is_revision_work: false,
    revision_number: 0,
    trigger_id: null,
    trigger_name: null,
    status_id: 35,
    status_name: 'Not Started',
    status_color: '#6b7280',
    blocker_reason: null,
    deliverable_link: '',
    notes: 'Awaiting client API sample payload credentials.'
  }
];

export const FALLBACK_EFFORTS = [];

export const FALLBACK_VERSIONS = [
  {
    id: 1,
    opportunity_id: 1,
    opportunity_name: 'Global Cloud Modernization',
    company: 'Apex Financial Services',
    version_number: 1,
    version_type_id: 51,
    version_type_name: 'Internal Draft',
    trigger_source_id: 42,
    trigger_source_name: 'Client Feedback',
    reason_category_id: 48,
    reason_category_name: 'Technical Clarification',
    change_summary: 'Initial architecture baseline and team staffing estimate draft.',
    commercial_changed: false,
    scope_changed: false,
    timeline_changed: false,
    estimated_rework_hours: 0.0,
    deadline_impact_id: 54,
    deadline_impact_name: 'No Impact',
    reviewed_by: 'admin',
    approved_by: 'jane_doe',
    proposal_link: '',
    pricing_link: ''
  }
];

export const FALLBACK_FEEDBACKS = [
  {
    id: 1,
    opportunity_id: 1,
    opportunity_name: 'Global Cloud Modernization',
    company: 'Apex Financial Services',
    version_id: 1,
    feedback_from_id: 58,
    feedback_from_name: 'Client Decision Maker',
    feedback_type_id: 62,
    feedback_type_name: 'Clarification Request',
    severity_id: 67,
    severity_name: 'Medium',
    severity_color: '#eab308',
    feedback_text: 'Requested additional detail on multi-region disaster recovery RTO and RPO guarantees.',
    action_required: true,
    owner: 'jane_doe',
    due_date: '2026-10-21',
    status_id: 71,
    status_name: 'In Progress',
    status_color: '#f59e0b',
    created_work_item_id: null
  }
];

export const FALLBACK_AUTOMATION_SETTINGS = {
  enable_missing_effort_reminder: true,
  effort_variance_threshold: 20.0,
  revision_threshold: 3,
  overload_threshold: 100.0,
  reminder_frequency: 'Weekly'
};

export const FALLBACK_TASK_TEMPLATES = [
  {
    id: 1,
    deliverable_type_id: 27,
    task_name: 'RFP Scope & Compliance Matrix Review',
    default_estimated_hours: 6.0,
    default_role_id: 74,
    sequence: 1
  },
  {
    id: 2,
    deliverable_type_id: 27,
    task_name: 'Technical Scoping & Architecture Design',
    default_estimated_hours: 16.0,
    default_role_id: 76,
    sequence: 2
  },
  {
    id: 3,
    deliverable_type_id: 27,
    task_name: 'RFP Response Drafting & Content Assembly',
    default_estimated_hours: 12.0,
    default_role_id: 76,
    sequence: 3
  }
];

export const FALLBACK_DASHBOARD_DATA = {
  summary: {
    total_opportunities: 3,
    active_tasks: 3,
    pipeline_value: 745000.0
  },
  opps_by_stage: [
    { stage_name: 'Discovery', stage_color: '#3b82f6', count: 1, total_value: 380000.0 },
    { stage_name: 'Submitted to Client', stage_color: '#06b6d4', count: 1, total_value: 240000.0 },
    { stage_name: 'POC(Proof Of Concept)', stage_color: '#8b5cf6', count: 1, total_value: 125000.0 }
  ],
  tasks_by_status: [
    { status_name: 'Not Started', status_color: '#6b7280', count: 1 },
    { status_name: 'In Progress', status_color: '#3b82f6', count: 2 }
  ],
  overdue_tasks: [],
  workload: [
    { username: 'jane_doe', weekly_capacity_hours: 45.0, role_name: 'Presales Owner', role_color: '#8b5cf6', total_assigned_hours: 24.0, active_tasks_count: 1, utilization_percent: 53.3, status: 'Normal' },
    { username: 'trisha_devadhe', weekly_capacity_hours: 40.0, role_name: 'Team Member', role_color: '#10b981', total_assigned_hours: 18.0, active_tasks_count: 1, utilization_percent: 45.0, status: 'Normal' },
    { username: 'vartika_jadon', weekly_capacity_hours: 35.0, role_name: 'Team Member', role_color: '#10b981', total_assigned_hours: 16.0, active_tasks_count: 1, utilization_percent: 45.7, status: 'Normal' }
  ],
  timeline_alerts: [],
  rework_hotspots: [],
  revision_threshold: 3
};
