// Shared fallback data for dropdown options and resource profiles
// Ensures that when database is initializing or unavailable, the application gracefully functions without 500 errors

export const FALLBACK_DROPDOWN_OPTIONS = [
  { id: 1, category: 'opportunity_type', option_name: 'Renewal', sort_order: 1, color: '#3b82f6', active: true },
  { id: 2, category: 'opportunity_type', option_name: 'New Business', sort_order: 2, color: '#10b981', active: true },
  { id: 3, category: 'opportunity_type', option_name: 'Change Request', sort_order: 3, color: '#8b5cf6', active: true },
  { id: 4, category: 'source', option_name: 'Inbound Inquiry', sort_order: 1, color: '#10b981', active: true },
  { id: 5, category: 'source', option_name: 'Sales Outreach', sort_order: 2, color: '#3b82f6', active: true },
  { id: 6, category: 'source', option_name: 'Partner Channel', sort_order: 3, color: '#8b5cf6', active: true },
  { id: 7, category: 'source', option_name: 'Existing Account Expansion', sort_order: 4, color: '#6366f1', active: true },
  { id: 8, category: 'source', option_name: 'Referral', sort_order: 5, color: '#f59e0b', active: true },
  { id: 9, category: 'deal_stage', option_name: 'Discovery', sort_order: 1, color: '#3b82f6', active: true },
  { id: 10, category: 'deal_stage', option_name: 'Submitted to Client', sort_order: 2, color: '#06b6d4', active: true },
  { id: 11, category: 'deal_stage', option_name: 'POC(Proof Of Concept)', sort_order: 3, color: '#8b5cf6', active: true },
  { id: 12, category: 'deal_stage', option_name: 'Won', sort_order: 4, color: '#10b981', active: true },
  { id: 13, category: 'deal_stage', option_name: 'Lost', sort_order: 5, color: '#ef4444', active: true },
  { id: 14, category: 'priority', option_name: 'Low', sort_order: 1, color: '#22c55e', active: true },
  { id: 15, category: 'priority', option_name: 'Medium', sort_order: 2, color: '#eab308', active: true },
  { id: 16, category: 'priority', option_name: 'High', sort_order: 3, color: '#f97316', active: true },
  { id: 17, category: 'priority', option_name: 'Critical', sort_order: 4, color: '#ef4444', active: true },
  { id: 18, category: 'complexity', option_name: 'Low', sort_order: 1, color: '#22c55e', active: true },
  { id: 19, category: 'complexity', option_name: 'Medium', sort_order: 2, color: '#eab308', active: true },
  { id: 20, category: 'complexity', option_name: 'High', sort_order: 3, color: '#f97316', active: true },
  { id: 21, category: 'complexity', option_name: 'Complex', sort_order: 4, color: '#ef4444', active: true },
  { id: 22, category: 'work_category', option_name: 'Proposal Writing', sort_order: 1, color: '#3b82f6', active: true },
  { id: 23, category: 'work_category', option_name: 'Product Demo', sort_order: 2, color: '#ec4899', active: true },
  { id: 24, category: 'work_category', option_name: 'Technical Scoping', sort_order: 3, color: '#8b5cf6', active: true },
  { id: 25, category: 'work_category', option_name: 'Pricing', sort_order: 4, color: '#06b6d4', active: true },
  { id: 26, category: 'work_category', option_name: 'Documentation', sort_order: 5, color: '#10b981', active: true },
  { id: 27, category: 'deliverable_type', option_name: 'RFP Response', sort_order: 1, color: '#ef4444', active: true },
  { id: 28, category: 'deliverable_type', option_name: 'Non RFP Response', sort_order: 2, color: '#3b82f6', active: true },
  { id: 29, category: 'deliverable_type', option_name: 'Proposal', sort_order: 3, color: '#f97316', active: true },
  { id: 30, category: 'deliverable_type', option_name: 'Presentation Deck', sort_order: 4, color: '#22c55e', active: true },
  { id: 31, category: 'deliverable_type', option_name: 'Brochure', sort_order: 5, color: '#2563eb', active: true },
  { id: 32, category: 'estimation_confidence', option_name: 'High', sort_order: 1, color: '#22c55e', active: true },
  { id: 33, category: 'estimation_confidence', option_name: 'Medium', sort_order: 2, color: '#eab308', active: true },
  { id: 34, category: 'estimation_confidence', option_name: 'Low', sort_order: 3, color: '#ef4444', active: true },
  { id: 35, category: 'task_status', option_name: 'Not Started', sort_order: 1, color: '#6b7280', active: true },
  { id: 36, category: 'task_status', option_name: 'In Progress', sort_order: 2, color: '#3b82f6', active: true },
  { id: 37, category: 'task_status', option_name: 'Review', sort_order: 3, color: '#a855f7', active: true },
  { id: 38, category: 'task_status', option_name: 'Blocked', sort_order: 4, color: '#ef4444', active: true },
  { id: 39, category: 'task_status', option_name: 'Completed', sort_order: 5, color: '#10b981', active: true },
  { id: 40, category: 'task_status', option_name: 'Cancelled', sort_order: 6, color: '#64748b', active: true },
  { id: 41, category: 'task_status', option_name: 'Terminated', sort_order: 7, color: '#ef4444', active: true },
  { id: 42, category: 'trigger_source', option_name: 'Client Feedback', sort_order: 1, color: '#3b82f6', active: true },
  { id: 43, category: 'trigger_source', option_name: 'Scope Expansion', sort_order: 2, color: '#10b981', active: true },
  { id: 44, category: 'trigger_source', option_name: 'Internal QA Review', sort_order: 3, color: '#f59e0b', active: true },
  { id: 45, category: 'trigger_source', option_name: 'Competitor Pressure', sort_order: 4, color: '#ec4899', active: true },
  { id: 46, category: 'trigger_source', option_name: 'Executive Mandate', sort_order: 5, color: '#8b5cf6', active: true },
  { id: 47, category: 'reason_category', option_name: 'Commercial Negotiation', sort_order: 1, color: '#059669', active: true },
  { id: 48, category: 'reason_category', option_name: 'Technical Clarification', sort_order: 2, color: '#2563eb', active: true },
  { id: 49, category: 'reason_category', option_name: 'Timeline Compression', sort_order: 3, color: '#d97706', active: true },
  { id: 50, category: 'reason_category', option_name: 'Scope Refinement', sort_order: 4, color: '#7c3aed', active: true },
  { id: 51, category: 'version_type', option_name: 'Internal Draft', sort_order: 1, color: '#6b7280', active: true },
  { id: 52, category: 'version_type', option_name: 'Client Submission', sort_order: 2, color: '#2563eb', active: true },
  { id: 53, category: 'version_type', option_name: 'Final Contract Version', sort_order: 3, color: '#16a34a', active: true },
  { id: 54, category: 'deadline_impact', option_name: 'No Impact', sort_order: 1, color: '#16a34a', active: true },
  { id: 55, category: 'deadline_impact', option_name: 'Minor Delay (< 3 Days)', sort_order: 2, color: '#d97706', active: true },
  { id: 56, category: 'deadline_impact', option_name: 'Major Delay (> 3 Days)', sort_order: 3, color: '#ea580c', active: true },
  { id: 57, category: 'deadline_impact', option_name: 'Critical Block / Reschedule', sort_order: 4, color: '#dc2626', active: true },
  { id: 58, category: 'feedback_from', option_name: 'Client Decision Maker', sort_order: 1, color: '#2563eb', active: true },
  { id: 59, category: 'feedback_from', option_name: 'Sales Account Manager', sort_order: 2, color: '#4f46e5', active: true },
  { id: 60, category: 'feedback_from', option_name: 'External Consultant', sort_order: 3, color: '#0d9488', active: true },
  { id: 61, category: 'feedback_from', option_name: 'Technical Review Panel', sort_order: 4, color: '#7c3aed', active: true },
  { id: 62, category: 'feedback_type', option_name: 'Clarification Request', sort_order: 1, color: '#3b82f6', active: true },
  { id: 63, category: 'feedback_type', option_name: 'Commercial Adjustment', sort_order: 2, color: '#10b981', active: true },
  { id: 64, category: 'feedback_type', option_name: 'Scope Revision', sort_order: 3, color: '#f59e0b', active: true },
  { id: 65, category: 'feedback_type', option_name: 'Defect / Error Correction', sort_order: 4, color: '#ef4444', active: true },
  { id: 66, category: 'severity', option_name: 'Low', sort_order: 1, color: '#22c55e', active: true },
  { id: 67, category: 'severity', option_name: 'Medium', sort_order: 2, color: '#eab308', active: true },
  { id: 68, category: 'severity', option_name: 'High', sort_order: 3, color: '#f97316', active: true },
  { id: 69, category: 'severity', option_name: 'Critical', sort_order: 4, color: '#ef4444', active: true },
  { id: 70, category: 'feedback_status', option_name: 'Open', sort_order: 1, color: '#3b82f6', active: true },
  { id: 71, category: 'feedback_status', option_name: 'In Progress', sort_order: 2, color: '#f59e0b', active: true },
  { id: 72, category: 'feedback_status', option_name: 'Resolved', sort_order: 3, color: '#10b981', active: true },
  { id: 73, category: 'role', option_name: 'Admin', sort_order: 1, color: '#ef4444', active: true },
  { id: 74, category: 'role', option_name: 'Presales Owner', sort_order: 2, color: '#8b5cf6', active: true },
  { id: 75, category: 'role', option_name: 'Sales Owner', sort_order: 3, color: '#3b82f6', active: true },
  { id: 76, category: 'role', option_name: 'Team Member', sort_order: 4, color: '#10b981', active: true },
  { id: 77, category: 'seniority', option_name: 'Principal Consultant', sort_order: 1, color: '#ef4444', active: true },
  { id: 78, category: 'seniority', option_name: 'Senior Consultant', sort_order: 2, color: '#8b5cf6', active: true },
  { id: 79, category: 'seniority', option_name: 'Consultant', sort_order: 3, color: '#3b82f6', active: true },
  { id: 80, category: 'seniority', option_name: 'Associate', sort_order: 4, color: '#10b981', active: true },
  { id: 81, category: 'department', option_name: 'Presales Solutions', sort_order: 1, color: '#8b5cf6', active: true },
  { id: 82, category: 'department', option_name: 'Enterprise Sales', sort_order: 2, color: '#3b82f6', active: true },
  { id: 83, category: 'department', option_name: 'Delivery / Consulting', sort_order: 3, color: '#10b981', active: true }
];

export const FALLBACK_RESOURCE_PROFILES = [
  {
    id: 1,
    username: 'admin',
    name: 'Adhesh',
    role_name: 'Admin',
    role_color: '#ef4444',
    seniority_name: 'Principal Consultant',
    department_name: 'Presales Solutions',
    weekly_capacity_hours: 40.0,
    standard_focus: 'Management, Solution Architecture',
    standard_focus_area: 'Management, Solution Architecture',
    skills: 'Management, Architecture, Strategy',
    password: 'admin123',
    is_active: true
  },
  {
    id: 2,
    username: 'jane_doe',
    name: 'Jane Doe',
    role_name: 'Presales Owner',
    role_color: '#8b5cf6',
    seniority_name: 'Senior Consultant',
    department_name: 'Presales Solutions',
    weekly_capacity_hours: 45.0,
    standard_focus: 'RFPs, Cloud Architecture',
    standard_focus_area: 'RFPs, Cloud Architecture',
    skills: 'RFPs, Cloud Architecture',
    password: 'jane123',
    is_active: true
  },
  {
    id: 3,
    username: 'trisha_devadhe',
    name: 'Trisha Devadhe',
    role_name: 'Team Member',
    role_color: '#10b981',
    seniority_name: 'Senior Consultant',
    department_name: 'Presales Solutions',
    weekly_capacity_hours: 40.0,
    standard_focus: 'RFPs, Cloud Architecture',
    standard_focus_area: 'RFPs, Cloud Architecture',
    skills: 'RFPs, Solutioning',
    password: 'trisha123',
    is_active: true
  },
  {
    id: 4,
    username: 'john_smith',
    name: 'John Smith',
    role_name: 'Sales Owner',
    role_color: '#3b82f6',
    seniority_name: 'Principal Consultant',
    department_name: 'Enterprise Sales',
    weekly_capacity_hours: 40.0,
    standard_focus: 'Sales, Relationship Management',
    standard_focus_area: 'Sales, Relationship Management',
    skills: 'Enterprise Sales, Account Management',
    password: 'john123',
    is_active: true
  },
  {
    id: 5,
    username: 'vartika_jadon',
    name: 'Vartika Jadon',
    role_name: 'Team Member',
    role_color: '#10b981',
    seniority_name: 'Consultant',
    department_name: 'Delivery / Consulting',
    weekly_capacity_hours: 35.0,
    standard_focus: 'Demo Prep, Frontend',
    standard_focus_area: 'Demo Prep, Frontend',
    skills: 'Prototyping, Demo Setup',
    password: 'vartika123',
    is_active: true
  },
  {
    id: 6,
    username: 'alice_williams',
    name: 'Alice Williams',
    role_name: 'Team Member',
    role_color: '#10b981',
    seniority_name: 'Associate',
    department_name: 'Delivery / Consulting',
    weekly_capacity_hours: 40.0,
    standard_focus: 'Pricing, Excel Modeling',
    standard_focus_area: 'Pricing, Excel Modeling',
    skills: 'Pricing Models, Analytics',
    password: 'alice123',
    is_active: true
  },
  {
    id: 7,
    username: 'vikrant_dhuriya',
    name: 'Vikrant Dhuriya',
    role_name: 'Team Member',
    role_color: '#10b981',
    seniority_name: 'Consultant',
    department_name: 'Delivery / Consulting',
    weekly_capacity_hours: 40.0,
    standard_focus: 'Solution Architecture & Integration',
    standard_focus_area: 'Solution Architecture & Integration',
    skills: 'Integration, Cloud Services',
    password: 'vikrant123',
    is_active: true
  },
  {
    id: 8,
    username: 'divyam_malliwal',
    name: 'Divyam Malliwal',
    role_name: 'Team Member',
    role_color: '#10b981',
    seniority_name: 'Consultant',
    department_name: 'Delivery / Consulting',
    weekly_capacity_hours: 40.0,
    standard_focus: 'Technical Consulting & Delivery',
    standard_focus_area: 'Technical Consulting & Delivery',
    skills: 'Technical Consultation, Fullstack',
    password: 'divyam123',
    is_active: true
  },
  {
    id: 9,
    username: 'finance_team',
    name: 'Finance Team',
    role_name: 'Finance Team',
    role_color: '#f59e0b',
    seniority_name: 'Senior Consultant',
    department_name: 'Presales Solutions',
    weekly_capacity_hours: 40.0,
    standard_focus: 'Financial & Commercial Review, Deal Approvals',
    standard_focus_area: 'Financial & Commercial Review, Deal Approvals',
    skills: 'Commercial Pricing, Deal Approvals',
    password: 'finance123',
    is_active: true
  }
];
